In [ ]:
from scipy import stats
import pandas as pd
import numpy as np

In [ ]:
#Data
durability=np.array([1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32, 0.85, 1.07, 1.48, 1.20, 1.33, 1.18, 1.22, 1.29])
n=len(durability)

In [ ]:
#Mean and Standard Devation
mean_durability=durability.mean()
std_durability=durability.std()
mean_durability,std_durability

(1.2386666666666666, 0.18661427836285438)

In [ ]:
#Confidence Interval
df = n - 1
t_critical=stats.t.ppf(0.995,durability)
t_critical

array([ 40.55185369,  16.48368062,  20.08233292,  90.04955521,
        29.27201895,  22.94715953,  24.94087204, 129.27429484,
        49.19832425,  18.41543225,  33.2390283 ,  24.41399137,
        35.0893006 ,  31.54790791,  26.64958477])

For calculating the T score or T critical at 99% the value used is 0.995

In [ ]:
#Margin of Error
margin_of_error_t=t_critical*std_durability/np.sqrt(n)
margin_of_error_t

array([1.95393428, 0.79424306, 0.96763909, 4.3389117 , 1.41043124,
       1.10567674, 1.20174099, 6.22890085, 2.37055235, 0.88732181,
       1.60157603, 1.17635398, 1.69072881, 1.52009176, 1.28407292])

The range within which we expect the true mean to lie with a specified level of confidence.

In [ ]:
#Confidence Interval t
t_confidence_interval=(mean_durability-margin_of_error_t,mean_durability+margin_of_error_t)
t_confidence_interval

(array([-0.71526761,  0.4444236 ,  0.27102758, -3.10024504, -0.17176457,
         0.13298992,  0.03692568, -4.99023418, -1.13188568,  0.35134486,
        -0.36290936,  0.06231268, -0.45206214, -0.28142509, -0.04540625]),
 array([3.19260094, 2.03290973, 2.20630575, 5.57757837, 2.6490979 ,
        2.34434341, 2.44040766, 7.46756751, 3.60921902, 2.12598848,
        2.84024269, 2.41502065, 2.92939547, 2.75875843, 2.52273959]))

Here are the 99% confidence interval for the mean number of characters printed before the print-head fails using the sample standard deviation.

In [ ]:
#Confidence Interval z
population_std=0.2
z_critical=stats.norm.ppf(0.995)
z_critical

2.5758293035489004

The Z Score for population standard deviation at 99% Confidence Interval

In [ ]:
#Margin of Error
margin_of_error_z=z_critical*population_std/np.sqrt(n)
margin_of_error_z

0.13301525327090588

In [ ]:
z_confidence_interval=(mean_durability-margin_of_error_z,mean_durability+margin_of_error_z)
z_confidence_interval

(1.1056514133957607, 1.3716819199375725)

Here are the 99% confidence interval for the mean number of characters printed before failure.